### ISSUE TITLE
API URL changing to https://digitalapi.auspost.com.au

### ISSUE THREAD

**Issue by okyanet** [fontis/auspost-api-php#6]
I've just received an email from Australia Post:

> As noted in our Postage Assessment Calculator (PAC) update in April, we've now migrated the PAC API to a new host URL: https://digitalapi.auspost.com.au 
> 
> Next, we're going to decommission the old PAC API URL: https://auspost.com.au/api

More details here:
http://auspost.com.au/pdfs/pac-api-update-2016.pdf

The urls in this repository will need to be adjusted.

**Comment by chnorton** [comment]
Thanks for bringing this up. Unless I'm mistaken, this change has already been made in the following commit:

https://github.com/fontis/auspost-api-php/commit/d0c1f7a58a50c715f795eea1d067d5305b16f558

If you think there are further updates that need to be made please let me know where and I'd be happy to review.

**Comment by okyanet** [comment]
My mistake... looks good to me. Sorry about that!
