### ISSUE TITLE
Auth Key header is failing psr-7 request validation

### ISSUE THREAD

**Issue by jishcem** [fontis/auspost-api-php#8]
When the [AUTH-KEY header](https://github.com/fontis/auspost-api-php/blob/master/src/HttpClient/Configurator.php#L73) is set as "AUTH-KEY: " instead of "AUTH-KEY" it is throwing [this exception](https://github.com/Nyholm/psr7/blob/master/src/MessageTrait.php#L180-L182) - "Header name must be an RFC 7230 compatible string."

**Comment by chnorton** [comment]
Thanks @jishcem have merged your PR that fixes this.

**Comment by jishcem** [comment]
@chnorton  Can you create a new tag with this new commit ?
